title: "Methoden der Dramenanalyse: analog und digital"
description: "Universität Potsdam · Freie Universität Berlin · Sommersemester 2023"
remote_theme: tuur29/pages-themes-cayman
plugins:
  - jemoji
